[build]
  command = "npm run export"
  functions = "lambda" #  netlify-lambda reads this

[[redirects]]
  from = "/studies/*"
  to = "/studies/[slug].html"
  status = 200
  force = true

[[redirects]]
  from = "/tasks/*"
  to = "/tasks/[slug].html"
  status = 200
  force = true

[[redirects]]
  from = "/surveys/*"
  to = "/surveys/[slug].html"
  status = 200
  force = true

[[redirects]]
  from = "/join/*"
  to = "/join/[step].html"
  status = 200
  force = true

[[redirects]]
  from = "/data/study"
  to = "/data/study.html"
  status = 200
  force = true

[[redirects]]
  from = "/signup/student/*"
  to = "/signup/student/[code].html"
  status = 200
  force = true

[[redirects]]
  from = "/proposals/*"
  to = "/proposals/[slug].html"
  status = 200
  force = true

[[redirects]]
  from = "/signup/mentor/*"
  to = "/signup/mentor/[code]/[invite].html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard/myclasses/assignments/*"
  to = "/dashboard/myclasses/assignments/[id].html"
  status = 200
  force = true

[[redirects]]
  from = "/do/task"
  to = "/do/task.html"
  status = 200
  force = true
